

-- public.customer_orders definition

-- Drop table

-- DROP TABLE customer_orders;

CREATE TABLE customer_orders (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	customer_id varchar(255) NULL,
	order_id int8 NULL,
	product_id varchar(255) NULL,
	quantity int4 NOT NULL,
	CONSTRAINT customer_orders_pkey PRIMARY KEY (id)
);


INSERT INTO public.customer_order_entity
(id, customer_id,order_id, product_id, quantity)
VALUES(1, 'nyla', 1,'sku1', 4);

INSERT INTO customer_order_entity
(id, customer_id, order_id, product_id, quantity)
VALUES(2, 'nyla', 1, 'sku2', 3);

INSERT INTO customer_order_entity
(id, customer_id, order_id, product_id, quantity)
VALUES(3, 'nyla', 1, 'sku3', 50);

INSERT INTO customer_order_entity
(id, customer_id, order_id, product_id, quantity)
VALUES(4, 'nyla', 1, 'sku1', 2);

create table products(
id text PRIMARY KEY,
DATA JSONB);


INSERT INTO products(id, data)
VALUES ('sku1','{"id" : "sku1", "name" : "Peanut butter"}');

INSERT INTO products(id, data)
VALUES ('sku2','{"id" : "sku2", "name" : "Jelly"}');

INSERT INTO products(id, data)
VALUES ('sku3','{"id" : "sku3", "name" : "Bread"}');


INSERT INTO products(id, data)
VALUES ('sku4','{"id" : "sku4", "name" : "Milk"}');