-- liquibase formatted sql
-- changeset liquibaseuser:1
CREATE TABLE customer_orders (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	customer_id varchar(255) NULL,
	order_id int8 NULL,
	product_id varchar(255) NULL,
	quantity int4 NOT NULL,
	CONSTRAINT customer_orders_pkey PRIMARY KEY (id)
);
-- rollback drop table customer_orders;

create table products(
id text PRIMARY KEY,
DATA JSONB);
-- rollback drop table products;
