server:
  port: 0
spring:
  data:
    gemfire:
      locators: localhost[10334]
      cache:
        name: server1
        server:
          port: 10111
  application:
    name: "spring-gf-redis-server"