server:
  port: 0
spring:
  data:
    gemfire:
      locators: localhost[10334]
      cache:
        name: server3
        server:
          port: 10133
gemfire:
  gemfire-for-redis-port: 63793
#  remote-distributed-system-id: 1