apiVersion: gemfire.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gf-redis
spec:
  # Avoid using the "latest" tag in production as it is harder to track which
  # version of the image is running and may cause members to upgrade
  # unexpectedly.
  image: registry.tanzu.vmware.com/pivotal-gemfire/vmware-gemfire:9.15.1
  # Set antiAffinityPolicy to "Cluster" or "Full" in production to limit the
  # chance of data loss.
  antiAffinityPolicy: None
  security:
    tls: {}
  metrics:
    emission: Default
  locators:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
#        cpu: 0.5
#      limits:
#        memory: 1Gi
#        cpu: 0.5
  servers:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
#        cpu: 1
#      limits:
#        memory: 1Gi
#        cpu: 1
    libraries:
      - name: gemfire-for-redis-apps
        container:
          image: registry.tanzu.vmware.com/tanzu-gemfire-for-redis-apps/gemfire-for-redis-apps:1.0.1
          path: "/gemfire-for-redis-apps/*"
          imagePullSecretRef:
            name: image-pull-secret
    overrides:
      jvmOptions: ["-Dgemfire-for-redis-enabled=true"]